import { GameProfile } from '../types';

export const DEFAULT_PROFILES: GameProfile[] = [
  {
    id: 'standard',
    name: 'Standard XInput Gamepad',
    genre: 'Universal Compatibility',
    coverUrl: 'https://images.unsplash.com/photo-1612287233207-6c84b11f71df?w=600&auto=format&fit=crop&q=80',
    description: 'Direct 1:1 hardware pass-through for any PC game supporting Xbox 360 / Xbox Series / Windows XInput.',
    mode: 'gamepad',
    recommendedLayout: 'dani.x240_pro',
    mapping: {
      'Left Stick': 'Movement Axis (LS)',
      'Right Stick': 'Camera Look Axis (RS)',
      'A': 'A / Cross Button',
      'B': 'B / Circle Button',
      'X': 'X / Square Button',
      'Y': 'Y / Triangle Button',
      'L1': 'Left Bumper (LB)',
      'R1': 'Right Bumper (RB)',
      'L2': 'Left Analog Trigger (LT)',
      'R2': 'Right Analog Trigger (RT)',
      'D-Pad': 'Directional Pad',
      'Touchpad': 'Mouse / Central Click',
    },
  },
  {
    id: 'cod',
    name: 'Call of Duty: Warzone / MW',
    genre: 'First-Person Shooter',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    description: 'Optimized response curves with tight aim deadzone, fast tactical triggers, and sprint-to-fire mapping.',
    mode: 'gamepad',
    recommendedLayout: 'dani.x240_fps',
    mapping: {
      'Left Stick': 'Sprint & Tactical Movement',
      'Right Stick': 'Precision ADS & Camera Aim',
      'L2': 'Aim Down Sights (ADS)',
      'R2': 'Fire Weapon',
      'L1': 'Tactical Equipment (Flash/Smoke)',
      'R1': 'Lethal Equipment (Frag/Semtex)',
      'A': 'Jump / Mantle Obstacle',
      'B': 'Slide / Crouch / Prone',
      'X': 'Reload / Interact',
      'Y': 'Switch Weapon / Armor Plate',
      'Touchpad': 'Scoreboard / Tactical Map',
    },
  },
  {
    id: 'gta_v',
    name: 'Grand Theft Auto V',
    genre: 'Open World Action',
    coverUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80',
    description: 'Hybrid layout dynamically shifting between on-foot third-person combat and high-speed vehicle cruising.',
    mode: 'gamepad',
    recommendedLayout: 'dani.x240_pro',
    mapping: {
      'Left Stick': 'Walk / Run / Vehicle Steering',
      'Right Stick': 'Camera / Vehicle Look',
      'R2': 'Accelerate Vehicle / Fire Weapon',
      'L2': 'Brake & Reverse / Lock-on Aim',
      'Y': 'Enter/Exit Car / Aircraft',
      'A': 'Sprint / Handbrake Drift',
      'B': 'Reload / Melee / Cinematic Cam',
      'X': 'Jump / Climb / Duck in Vehicle',
      'Touchpad': 'Change Radio Station / Weapon Wheel',
    },
  },
  {
    id: 'nfs',
    name: 'Need for Speed: Unbound',
    genre: 'Street Racing',
    coverUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80',
    description: 'Analog trigger throttle modulation, fine steering precision, and instant-access nitrous boost.',
    mode: 'gamepad',
    recommendedLayout: 'dani.x240_racing',
    mapping: {
      'Left Stick': 'Smooth Steer Angle',
      'R2': 'Progressive Throttle (0-100%)',
      'L2': 'Progressive Brake / Reverse',
      'A': 'Burst Nitrous Oxide',
      'B': 'E-Brake Drift Initiation',
      'X': 'Look Behind (Rearview Mirror)',
      'Y': 'Toggle Camera View',
      'Touchpad': 'Mini-map Zoom / Engine Sound',
    },
  },
  {
    id: 'rocket_league',
    name: 'Rocket League',
    genre: 'Physics Sports Action',
    coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Low-latency aerial response, digital air roll triggers, and instant flip reset controls.',
    mode: 'gamepad',
    recommendedLayout: 'dani.x240_pro',
    mapping: {
      'Left Stick': 'Pitch, Yaw & Ground Steering',
      'R2': 'Drive Forward',
      'L2': 'Reverse / Brake',
      'A': 'Jump / Dodge',
      'B': 'Rocket Boost',
      'X': 'Powerslide & Air Roll',
      'Y': 'Ball Cam Focus Toggle',
      'Touchpad': 'Quick Chat / Scoreboard',
    },
  },
  {
    id: 'keyboard_mouse',
    name: 'PC Keyboard & Mouse Emulator',
    genre: 'RTS, Strategy & Non-Gamepad Games',
    coverUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600&auto=format&fit=crop&q=80',
    description: 'Emulates real PC keyboard keystrokes and mouse cursor movement for older or indie games without gamepad support.',
    mode: 'keyboard_mapper',
    recommendedLayout: 'dani.x240_compact',
    mapping: {
      'Left Stick': 'WASD Keystrokes',
      'Right Stick': 'Mouse Cursor Velocity',
      'Touchpad': 'High-Precision Trackpad',
      'R2': 'Left Mouse Button (Click)',
      'L2': 'Right Mouse Button (Context)',
      'A': 'Spacebar (Jump / Confirm)',
      'B': 'Escape (Cancel / Menu)',
      'X': 'E Key (Interact / Use)',
      'Y': 'R Key (Reload / Refresh)',
      'L1': 'Shift Key (Sprint)',
      'R1': 'Control Key (Crouch)',
    },
  },
];
